sudo: required

language: generic

services:
  - docker
# Run tests
before_install:
  - docker build -t jordhancarvalho/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jordhancarvalho/react-test npm test

# Build all the prod Versions
after_success:
  - docker build -t jordhancarvalho/multi-client ./client
  - docker build -t jordhancarvalho/multi-nginx ./nginx
  - docker build -t jordhancarvalho/multi-server ./server
  - docker build -t jordhancarvalho/multi-worker ./worker
  # Login in to the docker CLI... It takes the DOCKER_PASS e usa ele como input do proximo command
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take the images and push to dockerHub
  - docker push jordhancarvalho/multi-client
  - docker push jordhancarvalho/multi-nginx
  - docker push jordhancarvalho/multi-server
  - docker push jordhancarvalho/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-007008111373"
  bucket_path: "multi-dockerv2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
